### ISSUE TITLE
Find a more robust way to implement the different shifts

### ISSUE THREAD

**Issue by arthurmloureiro** [LSSTDESC/Smokescreen#20]
Current shift types are contextual and could leave to issues:

Ex:
* `{'Omega_c': 0.3}` is a determinist shift
* `{'Omega_c': (0.2, 0.4)}` is a range
* `{'Omega_c': (-0.1, 0.1)}` is a delta shift

This can be problematic for parameters like w!

# Todo
- [x] remove it in the code
- [x] change code docstring
- [x] change usage documentation
- [x] unit tests
- [x] change the cosmic shear example
- [x] change the sne example
- [x] change the cosmic shear notebook
- [x] change the sne notebook

**Comment by arthurmloureiro** [comment]
I believe we should drop support for the "delta shift" approach and document that only the `range` approach is expected. This is similar to what we use in terms of a flat prior so it is sensible.
